### ISSUE TITLE
Sometimes, the translation for "What is your name" is getting wrong in spanish👀👀

### ISSUE THREAD

**Issue by chriz-ty** [chriz-ty/Multilingual-Translator#1]
It's like, sometimes, when we open the app from phone and try translating "what is your name" from English to Spanish, it translated wrong.. the output i got was something like "my name is kristine"(in spanish)... It's creepy though💀

**Comment by Enielect** [comment]
Hmm.. This is interesting because when I check [myMemory Website](https://mymemory.translated.net/en/English/Spanish/what-is-your-name) I get this api response every time i make the same query ("what is your name")
![translator-api](https://github.com/user-attachments/assets/e6a747e4-1865-4b7a-b712-0f7967232486)

I tried running the same input multiple times and I got the same api response, not sure why this is happening on your site though. 

A nice project you have here, I'll definitely give a look and hope to learn from it :)
